"""Original October editorial batch. Images are generated separately."""
import json, math
from pathlib import Path
R=Path(__file__).resolve().parents[1]
items=[]
def add(key,slug,title,category,excerpt,intro,ideas,faq,headlines,alts):
    sections=[]
    for i,(heading,body) in enumerate(ideas):
        s=dict(heading=f'{i+1}. {heading}',paragraphs=[body])
        if i<3:s.update(image=f'assets/generated/{slug}-{i+1:02}.webp',alt=alts[i],caption=heading+' — original AI-generated styling illustration.')
        sections.append(s)
    p=dict(slug=slug,title=title,category=category,excerpt=excerpt,intro=intro,sections=sections,status='published',featured=False,generatedImages=True,datePublished='2026-10-05',dateModified='2026-10-05',dateLabel='October 2026',cover=f'assets/generated/{slug}-01.webp',coverAlt=alts[0],pinCover=f'assets/generated/{slug}-pin-1.jpg',pinDescription=excerpt,faq=[dict(q=q,a=a) for q,a in faq],sources=[])
    p['readMinutes']=max(3,math.ceil(len(' '.join(intro+[b for a,b in ideas]).split())/200))
    items.append(dict(key=key,post=p,headlines=headlines))

add('halloween','minimal-halloween-nail-ideas','15 Minimal Halloween Nail Ideas for a Subtle October Manicure','Beauty & Nails',
'Try tiny ghosts, fine webs and understated pumpkin accents with 15 minimal Halloween nail ideas, plus simple tips for short nails and ordinary polish.',
['A Halloween manicure can be a small seasonal detail rather than a full costume. Start with a sheer base you already enjoy wearing, then reserve one or two nails for the motif. That leaves room for the design to read clearly even on a short nail.', 'These fifteen ideas include three illustrated starting points and twelve further variations. The images are styling concepts to show your nail artist, not a record of salon results. For home painting, use regular nail polish and allow each layer to dry before adding fine details.'],[
('One tiny white ghost','Paint a rounded white shape on a nude accent nail and taper its lower edge into two small curves. Add two pinprick black eyes after the white dries. Leave the surrounding nails plain so the little character remains the focus.'),
('A fine corner cobweb','Draw three thin lines spreading from one corner, then join them with shallow curves. Keep the web on a single nail and pair it with narrow black tips. A short liner brush and a nearly dry brush load help prevent heavy lines.'),
('A miniature pumpkin','Place a muted orange oval near the tip or sidewall, leaving a visible border of nude polish. A brown curved stem and one lighter stripe suggest the shape without filling the nail. A restrained gold fleck on a neighboring nail adds a warm finish.'),
('Black micro French tips','Trace a very narrow black band along each free edge. On short nails, keep the line fine and follow the natural curve; a thick stripe can visually shorten the nail. A sheer beige base makes this wearable beyond Halloween.'),
('A single crescent moon','Choose a cream base and one off-center gold or white crescent. Make the crescent with two overlapping curved strokes rather than a large filled circle. Keep the rest of the nail empty for a quiet celestial effect.'),
('Tiny bat silhouettes','Place one small bat on each ring finger. Two short angled wings and a small center dot are enough to suggest the shape. Practice on paper first and keep the silhouette narrower than half the nail.'),
('Dot-eye accents','Pair two tiny black dots on a milky base and leave the surrounding space untouched. Repeat on only two nails. This is a useful beginner option because the seasonal reference comes from the pairing rather than complicated line work.'),
('An orange side French','Sweep a narrow burnt-orange curve along one side of the tip. Leave the center mostly sheer. This asymmetrical detail works well when you want autumn color but no characters or symbols.'),
('A discreet stitched line','Draw a short black line diagonally across one accent nail and cross it with three tiny strokes. Stop well before the cuticle and free edge. Keeping it small prevents the stitching from becoming a heavy grid.'),
('A charcoal negative-space arc','Use a sheer pink base and draw one charcoal arc near the upper third of each nail. Keep the arc open at the sides. The design feels graphic without requiring an opaque dark manicure.'),
('One miniature star','Add a small four-point star to a taupe accent nail. Pull two fine intersecting strokes through a dot, then shorten the crosswise arms. A single star is easier to balance than a scatter of competing motifs.'),
('A soft smoky accent','Over a dry gray base, lightly dab a little darker polish with a sponge onto one nail. Keep the edges translucent and use a top coat to smooth the texture. Use ventilation and follow the polish label.'),
('A pumpkin-colored dot','Place one orange dot near the tip of each ring finger and leave it unadorned. It is the simplest route into the palette. Match the dot size across both hands so the result looks deliberate.'),
('A tiny cat-ear outline','Draw two small connected triangles along a curved black tip on an accent nail. The ears suggest a cat without needing whiskers or a face. Keep other nails in the same black-and-nude palette.'),
('An alternating cream and espresso finish','Alternate two solid shades, then add one small seasonal motif to a thumb. The base manicure remains simple while the thumb becomes an optional focal point. This also works with removable nail stickers under a compatible top coat.')],
[('Which design is easiest on short nails?','The pumpkin dot, tiny eyes and one ghost accent leave plenty of empty space. Avoid placing several motifs on the same short nail.'),('Do I need gel polish?','No. These ideas can be painted with ordinary polish or made with nail stickers. Follow drying times and product instructions; do not paint irritated or damaged skin.'),('How do I stop the design from smearing?','Let the artwork dry before top coating. Float a light layer over it without repeatedly brushing the same area; follow the drying guidance for your polish.')],
['15 Minimal\nHalloween Nails','Tiny Ghosts &\nSubtle Webs','A Little\nPumpkin Detail'],['Nude short nails with a tiny white ghost accent on cream linen','Fine black web accent and black micro French tips on nude nails','Nude manicure with a small orange pumpkin and a gold fleck'])

add('pumpkin','no-carve-pumpkin-decorating-ideas','12 No-Carve Pumpkin Decorating Ideas for a Softer Fall Display','Home & DIY',
'Decorate pumpkins with velvet bows, pressed leaves, paint and removable details. Twelve no-carve ideas with preparation, display and cleanup advice.',
['No-carve pumpkin decorating starts with a sound, dry surface and one clear idea. Choose firm pumpkins without soft spots, wipe off dirt and let them dry fully. Reusable faux pumpkins suit designs you want to keep for another year.', 'The first three ideas are illustrated; the remaining suggestions offer different materials and finishes. Paint, glue and sealers turn a pumpkin into decoration: keep decorated pumpkins out of food preparation and follow your local disposal guidance.'],[
('Burgundy velvet bows','Tie narrow velvet ribbon around the stem and let the tails fall along the ribs. Use cream pumpkins for a gentle contrast. Keep the knot loose enough to remove later, and group three different sizes without crowding the console.'),
('Pressed-leaf decoupage','Arrange dry, flat leaves before applying a thin layer of craft decoupage medium to a faux pumpkin. Work from the center of each leaf outward to reduce lifting. Let the finish cure according to its label and keep paper decorations indoors.'),
('Muted painted stripes and dots','Use sage, terracotta and cream craft paint on reusable pumpkins. Follow the ribs for stripes or use the end of a brush for dots. Apply thin coats and allow drying between colors; thicker paint can pool around the grooves.'),
('A single painted monogram','Choose one large letter rather than covering the pumpkin in wording. Lightly pencil its position on a painted faux surface and fill with a small brush. Turn the pumpkin on the shelf until the letter sits upright.'),
('Removable paper bats','Fold small black paper bats along their centers for a little dimension. Attach with a removable adhesive suitable for the surface. Keep the number low and cluster them diagonally so the arrangement looks like movement rather than a scattered pattern.'),
('A fabric-wrapped faux pumpkin','Set a small faux pumpkin in the center of a fabric square. Gather the corners toward the stem and tuck them under a ribbon tie. Thin cotton follows the shape more easily than heavy upholstery fabric.'),
('Pearl-style adhesive accents','Apply small flat-backed faux pearls in short arcs along alternating ribs. Test the adhesive on an inconspicuous spot first. Use a reusable pumpkin and keep loose decorative pieces away from young children and pets.'),
('A gingham ribbon band','Wrap a wide gingham ribbon around the middle and finish with a simple knot at the back. This suits a low shelf where the full circumference is visible. Repeat the ribbon color in a nearby napkin or small cushion.'),
('Painted wildflower stems','Paint three slim stems with tiny dots for flowers on a pale faux pumpkin. Give each stem a different height. Leaving half the surface blank makes the miniature painting easier to read from across the room.'),
('A two-tone dipped effect','Mask a horizontal line on a faux pumpkin and paint only the lower portion. Peel the tape according to the paint instructions for a clean edge. A cream upper half with a warm clay base works with neutral entryway furniture.'),
('A twine stem bow','Wrap a short piece of natural twine around the stem and tie a loose bow. Keep the body undecorated. The rough texture is enough to distinguish this from the velvet version without adding more craft supplies.'),
('A paper-leaf name tag','Cut a leaf from thick paper, write a guest name and tie it to a mini pumpkin stem. Use these as table place markers. Remove paper and string before disposal, and keep the tag clear of plates and serving dishes.')],
[('Should I use real or faux pumpkins?','Real pumpkins suit removable ribbon and tags. Faux pumpkins are easier to reuse and are a better base for paint, decoupage and glued decorations.'),('Can these go outside?','Plain ribbon and painted decorations are not automatically weatherproof. Use only products rated for the exposure, secure lightweight pieces and bring delicate displays indoors in wet weather.'),('How long will a real pumpkin last?','Condition, temperature and moisture matter, so there is no guaranteed duration. Keep it cool and dry, inspect regularly and remove it when soft spots or mold appear.')],
['12 No-Carve\nPumpkin Ideas','Pressed Leaves,\nPretty Pumpkins','Paint a Softer\nFall Palette'],['Cream pumpkins with burgundy velvet bows on a wooden console','Cream pumpkin decorated with pressed autumn leaves and flowers','Terracotta sage and cream pumpkins with dots and stripes'])

add('balcony','cozy-fall-balcony-ideas-small-spaces','10 Cozy Fall Balcony Ideas for Small Spaces','Home Decor',
'Make a small balcony feel inviting in fall with compact seating, warm lighting, portable textiles and a layout that keeps the walkway clear.',
['A cozy balcony needs room to use it. Measure the usable floor, the door swing and the path back indoors before choosing furniture. One comfortable seat often works better than a complete lounge set squeezed into a narrow space.', 'Use the first three illustrated layouts as starting points, then select the details that suit your weather and building rules. Textiles can come outside with you and return indoors afterward; the balcony does not need to stay fully dressed overnight.'],[
('A one-chair reading corner','Place one compact outdoor chair in the sheltered end, with a small table within reach. Add a rust throw and a cream cushion when you sit down. Keep the table out of the door swing and leave an unobstructed exit route.'),
('A folding bistro breakfast spot','Choose folding furniture that can store flat against an interior wall when not in use. Measure the chairs with someone seated, not just tucked under the table. A single small plant makes the setting feel complete without taking over the tabletop.'),
('A storage bench along the wall','Use a bench designed for outdoor conditions and sized for the available wall. Check that the lid opens fully and keep vents clear. Bring cushions inside unless their storage compartment is genuinely designed to keep them dry.'),
('One warm accent color','Repeat rust, burgundy or ochre in two small items instead of buying a full matching set. A throw and a pot cover are enough. Keep larger furniture neutral so the same balcony can change seasons easily.'),
('An outdoor-rated LED lantern','Place a stable LED lantern on the table or floor away from the path. Check its weather rating and battery instructions. Avoid open flames beside fabrics, plants or railings; a warm LED glow provides the atmosphere without that setup.'),
('A washable outdoor mat','Choose a low-profile mat that does not catch the door. Check that water can drain beneath it and lift it regularly to dry the surface. Natural indoor rugs may stay damp outside even under a partial roof.'),
('A compact seasonal planter','Choose plants for the actual light, wind and local temperatures, rather than their appearance alone. Use a pot with drainage and protect the floor below. Keep planters at floor level unless the building permits a properly secured alternative.'),
('A portable blanket basket','Carry out a small basket containing a throw and reading materials only when you need them. Bring it back inside afterward. This is especially useful when the balcony is too exposed for permanent soft furnishings.'),
('A restrained string-light line','Run outdoor-rated lights along a permitted mounting point without loose trailing cables. Follow the manufacturer’s installation directions and building rules. One short line is usually enough for a small balcony; keep fittings away from the door mechanism.'),
('An easy evening reset','Before going indoors, remove cups, dry any spills and collect cushions. Keep lightweight accessories from blowing away. A five-minute reset protects the space and means the chair is ready for the next crisp morning.')],
[('Can I do this without drilling?','Yes: freestanding furniture, portable lanterns and floor planters do not need wall fixings. Check your lease and building rules before attaching anything.'),('How do I make a very narrow balcony comfortable?','Start with one chair and a small movable table. Test the door and walkway before adding plants or lighting.'),('Do I need an outdoor heater?','No. Dress for the weather and use a blanket for short visits. Heating devices may be restricted and require clearances that a tiny balcony cannot provide.')],
['10 Cozy Fall\nBalcony Ideas','Your Tiny\nAutumn Café','Small Balcony,\nWarm Evenings'],['Small balcony reading chair with rust throw and warm lantern','Compact folding bistro table and chairs on an autumn balcony','Narrow balcony bench with olive cushions and warm lights'])

add('snacks','easy-halloween-party-snacks','9 Easy Halloween Party Snacks for a Small Gathering','Food & Drinks',
'Plan nine playful Halloween party snacks, from ghost mini pizzas to mummy pastries, with small-batch quantities and a practical prep order.',
['Choose two savory snacks and one sweet option for a small gathering, then scale for your guest count and whether you are also serving dinner. Repeating a short list of ingredients is easier than preparing nine recipes at once.', 'These are original small-batch recipe ideas, not kitchen-tested claims. Oven performance and ingredient brands vary: use the visual doneness checks alongside the approximate times. Keep chilled ingredients refrigerated until assembly and put out small platters that can be replenished.'],[
('Ghost mini pizzas','For 6 pieces, split 3 English muffins and spread each half with about 1 tablespoon pizza sauce. Bake on a tray at 200°C / 400°F for about 5 minutes. Add ghost-shaped pieces cut from 100 g sliced mozzarella and tiny olive eyes, then bake another 3–5 minutes until hot and melted. Watch closely so the ghost shape does not disappear.'),
('Mummy pastry sausages','For 8 pieces, wrap 8 fully cooked small sausages with narrow strips cut from about 250 g ready-rolled puff pastry. Leave a small gap for the face. Bake at 200°C / 400°F for roughly 18–22 minutes, or follow the pastry pack, until puffed and golden and the sausages are hot throughout. Add mustard-dot eyes after baking.'),
('White-chocolate strawberry ghosts','Wash and thoroughly dry 12 strawberries. Melt about 150 g white chocolate gently in short microwave bursts, stirring between each. Dip the berries, set on parchment and add small dark-chocolate eyes once the coating firms. Chill until set and serve soon after making for the best texture.'),
('Clementine pumpkins','Peel 6 clementines and insert a short, thin celery piece into the center of each. Prepare shortly before serving to keep the fruit fresh. This is a lighter option beside pastry snacks; adjust piece sizes for the age of the guests.'),
('Olive spider crackers','Spread 12 crackers with a total of about 100 g cream cheese. Halve pitted black olives for bodies and cut remaining olives into thin leg pieces. Assemble near serving time so the crackers stay crisp, and keep the cream cheese chilled until needed.'),
('Monster apple bites','Cut 2 apples into wedges and blot the cut faces dry. Spread a thin layer of sunflower seed butter on half the wedges, add a few small marshmallows as teeth and top with another wedge. Check ingredient labels for guest allergies and make these shortly before serving.'),
('Cheesy tortilla bats','Cut bat shapes from 4 small tortillas using a food-safe cutter. Lightly brush with oil, sprinkle with about 40 g grated cheese and bake at 180°C / 350°F for roughly 6–9 minutes until crisp at the edges. Serve beside a separate bowl of salsa so they do not soften.'),
('Chocolate pretzel webs','Arrange small pretzel sticks in six radial clusters on parchment. Drizzle roughly 100 g melted chocolate across each cluster in connected circles. Add a small chocolate dot in the center and leave to set fully before lifting. Store cool and dry until the party.'),
('Spooky popcorn cups','Divide 6 cups plain popped popcorn among paper cups. Drizzle with about 60 g melted white chocolate and scatter a little edible orange decoration. Let the chocolate set before serving. Keep popcorn for guests old enough to eat it safely and offer a suitable alternative for younger children.')],
[('What can I make ahead?','Chocolate pretzel webs can be prepared earlier and stored cool and dry. Assemble cracker snacks and cut fruit close to serving; bake pizzas just before guests eat.'),('How do I simplify the shopping list?','Choose ghost pizzas, clementines and one chocolate snack. This gives a warm item, fruit and a sweet item without buying ingredients for all nine ideas.'),('How should I handle allergens?','Ask guests beforehand and read every ingredient label, including pastry, chocolate and spreads. Keep utensils separate where needed; do not describe a dish as allergen-free without checking all ingredients and handling.')],
['9 Easy\nHalloween Snacks','Golden Little\nMummy Bites','Sweet Strawberry\nGhosts'],['Mini pizzas with mozzarella ghost shapes and black olive eyes','Golden pastry mummy sausages with mustard eyes on a platter','Strawberries dipped in white chocolate with small dark ghost faces'])

add('brown','brown-french-tip-nail-ideas','12 Brown French Tip Nail Ideas from Espresso to Caramel','Beauty & Nails',
'Explore twelve brown French tip nail ideas for short, oval and almond nails, with espresso, caramel and chocolate combinations and clean-line tips.',
['Brown French tips change character with the undertone and the width of the smile line. Espresso creates a sharper contrast, caramel feels softer, and a milk-chocolate shade bridges the two. Start with a sheer base that works with your own skin tone rather than trying to copy a single universal nude.', 'Three illustrated looks open the guide, followed by nine variations to discuss with a nail artist or try with ordinary polish. Keep the line proportions consistent across the hand; the design does not need a long extension to look polished.'],[
('Espresso micro tips on short nails','Follow the natural free edge with a thin espresso line. Keep the band slightly narrower at the sides to avoid a blocky finish. A rounded-square shape and sheer pink-beige base make this an easy everyday interpretation.'),
('Caramel tips on almond nails','Use a warm caramel shade and a softly curved smile line. Leave enough nude area visible for the color to read as a tip rather than a half-painted nail. Keep the almond point rounded and balanced across the set.'),
('Chocolate with a fine gold outline','Paint the chocolate tip first and let it dry, then trace a hairline gold accent along its inner curve. The metallic line should separate the colors rather than dominate them. One accent nail is enough if you prefer a quieter version.'),
('A matte cocoa finish','Choose cocoa tips and a compatible matte top coat. Test the finish because a matte layer changes how dark the brown appears. Keep the shape simple so the texture becomes the main detail.'),
('Alternating brown shades','Use espresso, cocoa and caramel across the hand while keeping the tip shape identical. Arrange the shades intentionally from light to dark. Too many different line widths can make a restrained palette look busy.'),
('A diagonal mocha French','Sweep mocha from one side of the free edge toward the opposite corner. Repeat the direction on each hand in a mirrored arrangement. This can make a short nail feel more graphic without adding length.'),
('A double brown smile line','Paint a narrow tip, then add a second fine curve just below it. Leave a slim nude gap between the two. This needs a steady liner brush, so simplify to one accent nail if the available space is small.'),
('Cream and espresso pairing','Use espresso French tips on most nails and one cream solid accent. Match the warmth of the cream to the base color. Keep that accent free of additional patterns so it supports the manicure rather than competing with it.'),
('A soft rounded cocoa tip','Follow an oval free edge with a medium-width cocoa band. Avoid pulling the corners too far down the sides. This is a softer alternative to a deep, sharply pointed salon French.'),
('A brown side outline','Keep the tip narrow and extend the color slightly down one side of the nail. Stop before the cuticle. The small extension makes the design asymmetrical while preserving the sheer base.'),
('A tiny dot beneath the tip','Add one small brown dot below the smile line on a ring finger. Center it carefully and leave the other nails plain. Repeating the same polish means no extra palette decisions are needed.'),
('A translucent toffee tip','Choose a sheer brown polish and build a light tint at the free edge with thin layers. The effect is softer than an opaque stripe. Let each coat dry before adding the next to avoid ridges at the smile line.')],
[('Which brown works best on short nails?','Any brown can work, but a thin tip leaves more of the nail visible. Espresso gives contrast; caramel makes the edge feel softer.'),('Can I use French-tip guides?','Yes, with ordinary polish if the base is fully dry. Remove the guide carefully according to its directions and finish with a compatible top coat.'),('Should every nail use the same shade?','A single shade looks cohesive, while a limited three-brown palette adds variation. Keep the shape and width consistent either way.')],
['12 Brown\nFrench Tip Ideas','Caramel Tips,\nSoft Autumn Style','Chocolate Tips\nWith a Gold Detail'],['Short nude nails with thin espresso French tips on taupe linen','Almond nails with caramel French tips holding a ceramic mug','Chocolate French tips outlined with a fine gold curve'])

add('table','thrifted-halloween-table-decor-ideas','10 Thrifted Halloween Table Decor Ideas with Vintage Character','Home Decor',
'Build a Halloween table with secondhand candlesticks, amber glass and reusable textiles, plus practical checks for table space and food-safe serving.',
['A thrifted Halloween table feels collected when the colors connect, even if the objects do not match. Choose a small palette—cream, charcoal and brass, for example—then shop your own cupboards before buying anything.', 'Use old objects for decoration and known food-safe pieces for food. Chips, uncertain glazes and decorative coatings are reasons to keep a vintage find off the serving line. The first three illustrated arrangements show different starting points; combine only what leaves comfortable room for your guests.'],[
('Brass holders and a charcoal runner','Gather two or three secondhand candleholders at different heights and use well-fitting flameless tapers. Place them on a charcoal runner with small cream pumpkins. Keep the tallest piece out of guests’ sightlines across the table.'),
('Amber bottles with bare branches','Use clean decorative amber bottles as small vases, away from the plates. Trim branches so they do not reach faces or food. Burgundy napkins connect the warm glass to the rest of the setting without needing themed dishes.'),
('A vintage tray centerpiece','Use an old tray to contain ceramic pumpkins and an LED lantern. Check its feet and protect the tabletop underneath. A tray makes cleanup easy: lift the entire arrangement away when serving dishes need the space.'),
('Mismatched cream plates','Choose sound, food-safe plates in related cream shades. Do not use a decorative or uncertain vintage glaze for eating. Mixing known safe modern plates with antique decorative pieces gives the same collected look without relying on unknown tableware.'),
('Secondhand fabric as a runner','A clean piece of washable fabric can become a runner without permanent alteration. Fold raw edges underneath and press the fold. Check that the cloth will not trail into laps or snag chair legs.'),
('Small framed silhouette cards','Use miniature secondhand frames for simple paper moon or bat silhouettes. Place them along a sideboard rather than in front of each plate. Keep original valuable artwork intact and use removable inserts.'),
('Dark ribbon on napkins','Tie clean cloth napkins with narrow charcoal ribbon and a simple knot. Remove all decorative pieces before using the napkin. Repeating one detail at every setting brings order to otherwise mismatched finds.'),
('An old book display on the sideboard','Stack a few inexpensive books with dark cloth covers beside a ceramic pumpkin. Keep books away from spills and hot dishes. This adds height to a display without occupying the eating surface.'),
('Clear glass and paper shadows','Place a removable paper silhouette outside a glass vessel and use a battery LED light inside. Keep paper away from heat and use no real flame. A plain glass jar often works better than buying a specialized seasonal lantern.'),
('A restrained found-object palette','Finish by removing one item from each crowded cluster. Leave room for elbows, water glasses and serving utensils. Reuse the brass, linens and glass after Halloween by changing only the pumpkins and paper details.')],
[('What should I look for when thrifting?','Stable candleholders, washable linens and sound decorative trays are useful starting points. Check cracks, wobbling bases and odors before buying.'),('Can I serve food on vintage plates?','Only when you know they are intended and safe for food use. Uncertain glazes, chips and decorative finishes belong in the display, not under food.'),('How do I avoid a cluttered table?','Choose one central arrangement and repeat a small detail at each place. Move tall or bulky decorations to a sideboard before serving.')],
['10 Thrifted\nHalloween Table Ideas','Amber Glass &\nAutumn Evenings','A Vintage Tray,\nA Little Halloween'],['Vintage brass candleholders and white pumpkins on a charcoal table runner','Amber bottle vases and burgundy napkins on a Halloween table','Vintage tray with ceramic pumpkins and a warm LED lantern'])

add('apple','apple-cinnamon-desserts-fall','8 Apple Cinnamon Desserts for Cozy Fall Evenings','Food & Drinks',
'Make eight small-batch apple cinnamon desserts, including crumble cups, puff pastry roses and baked apples, with quantities and visual doneness checks.',
['Apple desserts become easier when you choose the texture first. Small diced pieces soften quickly in a crumble, thin slices bend into pastry roses, and halved apples hold a filling. Taste your apples before adding sugar: a sweet variety needs less than a sharp one.', 'These original recipe starting points have not been presented as kitchen-tested recipes. Timing varies with the apple variety, dish size and oven. Check tenderness with a knife and look for cooked pastry or a golden topping rather than relying only on the clock.'],[
('Individual apple crumble cups','For 4 oven-safe ramekins, toss 3 peeled diced apples with 1 tablespoon brown sugar, 1 teaspoon cinnamon and 1 teaspoon lemon juice. Rub 40 g cold butter into 50 g flour, 40 g rolled oats and 30 g brown sugar. Divide fruit and topping between dishes; bake at 180°C / 350°F for about 25–35 minutes until bubbling and tender.'),
('Puff pastry apple roses','For 6 roses, thinly slice 2 cored red apples and soften the slices briefly in hot water with a little lemon juice; drain and dry. Cut about 250 g ready-rolled puff pastry into 6 strips, brush with 2 tablespoons warmed apricot jam mixed with ½ teaspoon cinnamon, overlap apple slices along one edge, fold and roll. Bake in a greased muffin tin at 190°C / 375°F for about 35–45 minutes until the pastry is cooked through; loosely cover if the apple edges darken early.'),
('Oat-filled baked apple halves','Halve and core 2 large apples. Mix 30 g oats, 20 g chopped walnuts, 20 g softened butter, 1 tablespoon maple syrup and ½ teaspoon cinnamon. Divide into the cavities and place in a small baking dish with a splash of water. Bake at 180°C / 350°F for about 30–40 minutes until a knife enters the flesh easily.'),
('Quick skillet cinnamon apples','Cook 2 sliced apples with 15 g butter over medium heat for about 5 minutes, stirring. Add 1 tablespoon brown sugar, ½ teaspoon cinnamon and 2 tablespoons water. Cover briefly, then uncover and cook until tender with a light syrup. Serve warm over ice cream or yogurt; this makes about 2 portions.'),
('Apple hand pies','Cut one approximately 250 g sheet of ready-rolled pastry into 8 rectangles. Fill 4 with a cooled mixture of 1 finely diced apple, 1 tablespoon sugar, ½ teaspoon cinnamon and 1 teaspoon flour. Add the remaining rectangles, seal edges, vent tops and brush with beaten egg if desired. Bake at 200°C / 400°F for about 20–25 minutes until well risen and golden, checking the pastry pack instructions.'),
('Layered apple yogurt cups','Cool a batch of the skillet apples completely. Layer between 250 g plain thick yogurt and 40 g granola in 2 glasses. Add the granola immediately before serving if you want crunch. This turns cooked fruit into a chilled dessert without making a second dough or batter.'),
('Cinnamon apple toast','Toast 2 thick bread slices and spread with a little butter. Top with warm skillet apples, divided evenly, and finish with a spoonful of plain yogurt. Serve immediately so the toast stays crisp. Use a plate rather than a serving board to catch the fruit syrup.'),
('Apple oat dessert cookies','Mix 80 g oats, 60 g flour, ½ teaspoon baking powder, ½ teaspoon cinnamon and a pinch of salt. Stir in 50 g melted cooled butter, 40 g brown sugar and 1 beaten egg, then fold in 80 g finely diced apple. Scoop 10 portions onto a lined tray and bake at 180°C / 350°F for roughly 14–18 minutes until the edges set and turn golden. Cool on the tray before moving; these are soft fruit cookies, not crisp biscuits.')],
[('Which apples should I choose?','Use firm apples for pastry roses and halved baked apples. A mixture of sweet and tart apples works in crumble; adjust added sugar to taste.'),('Can I prepare the crumble ahead?','Keep prepared fruit and topping separately refrigerated, then assemble before baking. The topping can become damp when it sits directly on the fruit.'),('Can I skip the nuts?','Yes. In the baked apples, replace the walnuts with a little more oats if that suits your ingredients. Check all labels and handling requirements for guests with allergies.')],
['8 Apple &\nCinnamon Desserts','Pretty Apple\nPastry Roses','Warm Baked\nApple Evenings'],['Apple cinnamon crumbles with golden oat topping in ivory ramekins','Golden apple puff pastry roses with red peel edges on a cake stand','Baked apple halves filled with oats cinnamon and walnuts'])

add('plaid','plaid-nail-designs-autumn','12 Plaid Nail Designs for Autumn in Burgundy, Brown and Green','Beauty & Nails',
'Explore twelve autumn plaid nail designs, from burgundy accent nails to fine neutral checks, with spacing tips for short nails and simple polish tools.',
['A plaid manicure works best when the lines have a clear hierarchy. Choose one base color, one broad stripe color and one fine-line accent. You do not need an exact fabric tartan: a small, readable arrangement is more effective on a curved nail.', 'Begin with one or two accent nails, as shown in the first three illustrated examples. The additional variations change the palette, stripe placement or amount of pattern. Practice the grid on a spare tip or paper before painting your hand.'],[
('Burgundy and cream accents','Paint most nails glossy burgundy and leave two cream accent nails for the grid. Add a broad burgundy stripe and a thin crossing line. Keeping the pattern on just two nails makes it readable on short oval shapes.'),
('Cocoa and beige checks','Start with beige and use milk chocolate for the main horizontal and vertical bands. Add a fine darker line beside one band to create depth. Match the remaining nails to the milk-chocolate shade rather than adding a fourth color.'),
('Forest green and cream plaid','Use a cream base for two accent nails and forest green on the others. Cross two fine green stripes with a slightly wider band. Leave a clear margin near the cuticle so the pattern does not look crowded.'),
('A fine taupe windowpane','Draw evenly spaced taupe lines on an ivory base, keeping every stroke similar in width. This is closer to a windowpane check than a layered tartan. Its simplicity makes it a good practice design before adding multiple stripe widths.'),
('A single plaid ring finger','Keep nine nails in one solid color and use the ring finger as the patterned detail. Repeat that solid shade inside the grid. The result feels connected even when the accent has a lighter base.'),
('Plaid French tips','Restrict the grid to a wide tip area and keep the lower nail sheer. Paint the tip background before adding the crossing stripes. This is easier on a little more length; on very short nails, use one full accent instead.'),
('Rust and cream with a dark line','Use muted rust for broad bands and a narrow espresso line for contrast. Avoid pure black if you want a softer palette. A cream base leaves enough brightness for the overlapping colors to remain distinct.'),
('A diagonal check','Rotate the direction of the crossing lines so they form diamonds across the nail. Keep the angles consistent and start from a central crossing point. This is more forgiving when used on one nail instead of an entire set.'),
('Navy and warm beige','Pair a beige base with navy stripes and one very fine cream highlight. Keep the blue deep and slightly muted for an autumn feel. Finish the other nails in navy to frame the lighter pattern.'),
('A sheer negative-space grid','Use a clear or sheer pink base and two thin brown crossing lines. Allow plenty of space between them. The nail’s natural appearance becomes part of the design and keeps the finish lighter than an opaque plaid.'),
('A matte plaid accent','Use a compatible matte top coat on the patterned nails and a glossy finish on the solid ones. Let the grid dry first to avoid dragging the lines. Test the matte product because it can change the contrast between colors.'),
('A tiny metallic crossing','Complete a brown-and-cream plaid, then add one fine gold crossing line. Keep metallic polish away from every other intersection. A single glint provides detail without turning the grid into a glitter-covered surface.')],
[('How many colors do I need?','Three are enough: a base, a stripe color and a fine accent. Start with two if you are learning to control line spacing.'),('Can I do plaid on short nails?','Yes. Use fewer lines and one or two accent nails. A fine windowpane design is often easier to read than a dense tartan.'),('What helps make the lines straight?','Support your painting hand, turn the finger as needed and use a small liner brush with very little polish. Let each layer dry before crossing it with another color.')],
['12 Plaid Nails\nfor Autumn','Cocoa Checks &\nCream Details','Forest Green\nPlaid Moments'],['Short burgundy manicure with fine cream and burgundy plaid accents','Cocoa and beige plaid accent nails with chocolate solid nails','Forest green nails with cream and green plaid accents'])

if __name__=='__main__':
    existing=json.loads((R/'data/posts.json').read_text())
    slugs={x['post']['slug'] for x in items}
    (R/'data/posts.json').write_text(json.dumps([x['post'] for x in items]+[p for p in existing if p['slug'] not in slugs],ensure_ascii=False,indent=2)+'\n')
    (R/'data/fall-eight-2026-10-05.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
    print('Prepared eight original articles with',sum(len(x['post']['sections']) for x in items),'individual ideas.')
