"""Original grooming and fragrance editorial batch, 5 October 2026."""
import json, math
from pathlib import Path
R=Path(__file__).resolve().parents[1]
items=[]
def add(key,slug,title,cat,excerpt,intro,sections,faq,headlines,alts):
 ss=[]
 for i,(h,b) in enumerate(sections):
  s=dict(heading=h,paragraphs=b.split('|'))
  if i<3:s.update(image=f'assets/generated/{slug}-{i+1:02}.webp',alt=alts[i],caption=h+' — AI-generated editorial illustration.')
  ss.append(s)
 p=dict(slug=slug,title=title,category=cat,excerpt=excerpt,intro=intro,sections=ss,status='published',featured=False,generatedImages=True,datePublished='2026-10-05',dateModified='2026-10-05',dateLabel='October 2026',cover=ss[0]['image'],coverAlt=alts[0],pinCover=f'assets/generated/{slug}-pin-1.jpg',pinDescription=excerpt,faq=[dict(q=q,a=a) for q,a in faq],sources=[])
 p['readMinutes']=max(3,math.ceil(len(' '.join(intro+[b for h,b in sections]).split())/200))
 items.append(dict(key=key,post=p,headlines=headlines))
G="Men's Grooming";F='Beauty & Fragrance'
add('beard','beard-fade-guide','Beard Fade Guide: Short, Medium and Full Beard Options',G,
'Choose a beard fade by length, density and upkeep, with practical barber consultation tips and three illustrated starting points.',
['A beard fade is a gradual change in length, usually around the sideburn, that connects the haircut to the beard. The position of that transition matters as much as the overall beard length. A low, subtle blend can keep a full beard looking full; a higher transition can expose more of the cheek.', 'Use these illustrations to discuss shape with your barber. They are visual concepts, not before-and-after results or promises about how a cut will look on your growth pattern.'],[
('Short beard, quiet transition','A short beard benefits from a transition that does not remove its strongest areas. Ask to keep visible coverage along the jaw and soften the sideburn rather than taking a wide strip down to skin. If your cheek growth is sparse, preserving the natural line may make more sense than carving a high, sharp edge.|Bring a side-view photograph showing the amount of skin you want visible. Explain whether you like a soft finish or a precise outline; those are separate decisions from the fade itself.'),
('Medium beard, balanced sides','With a medium beard, decide how much width to retain beside the mouth before choosing the fade height. A compact sideburn and fuller lower beard can create a deliberate shape without aggressively thinning the cheek. Ask your barber to show you the outline from the front and both sides before shortening the body.|Growth often differs across the face. Matching the visual outline may require different adjustments on each side rather than identical clipper settings.'),
('Full beard, preserved weight','For a longer beard, place the emphasis on connecting the sideburn while retaining the weight below. Choose a rounded, squared or gently tapered lower outline according to your preference and actual density. Do not assume that a full beard needs an especially high fade.|Comb the beard into its ordinary resting position before discussing the cut. A shape that only looks even when pulled straight may be harder to reproduce during your daily routine.'),
('What to say in the barber chair','Try: “Keep the fullness along my jaw, make the transition low around the sideburn, and show me where the cheek and neckline will sit before outlining.” Add whether the mustache should connect and how much lip coverage you want. Bring one preferred reference and one example that feels too short.|Guard numbers are not a universal design language: tool systems and technique vary. Photos, transition placement and retained length communicate the result more reliably than requesting one number for the whole beard.'),
('Make upkeep part of the choice','Ask which areas you can tidy between appointments and which should wait for the next blend. At home, comb first and remove only obvious stray ends if you are comfortable doing so. Repeatedly chasing the fade upward can gradually remove the shape you wanted to keep.|Choose the next appointment based on how quickly the transition loses definition for you. A softer blend tolerates visible growth differently from a skin-level finish; no single schedule suits every beard.')],
[('Can a patchy beard have a fade?','Sometimes. The transition should work around stronger and weaker growth. Ask a barber whether retaining more cheek coverage would produce a more balanced result.'),('Does a beard fade require a skin fade haircut?','No. It can connect to longer sides or a taper. Show the barber how you want the haircut and beard to meet.'),('Which length is easiest to maintain?','The easiest option depends on your growth and expectations. A subtle transition usually requires less precision to keep looking intentional than a very sharp contrast.')],
['Find Your\nBeard Fade','A Balanced\nMedium Beard','Full Beard,\nSofter Sides'],['Side profile of a short beard with a low sideburn transition','Medium rounded beard with a blended sideburn and textured crop','Full long beard with preserved jaw coverage and tapered sideburn'])
add('italian','italian-beard-fade-guide','Italian Beard Fade: How to Explain the Shape to Your Barber',G,
'Understand the Italian beard fade label and choose the sideburn, cheek line, mustache connection and lower outline that suit your beard.',
['“Italian beard fade” is a useful search phrase, but it is not a standardized barber specification. References often show a controlled sideburn transition, a tidy mustache and a deliberately shaped short beard. Different barbers may interpret the label differently.', 'The practical approach is to describe the parts of the look you like. The illustrations show three possible directions, and none depends on having a particular nationality or hair texture.'],[
('Short beard with a low blend','This version keeps the transition close to the sideburn and leaves enough beard along the jaw to read as a continuous shape. A natural cheek line makes the finish softer than a heavily drawn outline. Ask for the fade position first, then discuss how much bulk should remain around the chin.|If your chosen photograph shows unusually dense coverage, explain that you want its overall shape rather than expecting your beard to reproduce every edge.'),
('Swept-back hair and a connected mustache','A brushed-back haircut makes the sideburn connection especially visible. Keep the mustache connection as a separate choice: you may prefer a continuous line into the beard or a little separation around the mouth. Ask your barber to preserve whichever areas provide the coverage you enjoy.|Check the beard when speaking and smiling as well as at rest. Lip coverage and the corners of the mouth affect everyday comfort, even if the outline looks excellent in a still photograph.'),
('Curly crop with a rounded lower outline','The same tidy concept can work with a curly crop and a short, rounded beard. The goal is a clear connection between the sides and the beard, with enough weight below to keep the silhouette coherent. The curl pattern on top does not dictate one required beard shape.|View the result head-on. A side photograph can show the fade beautifully while hiding unwanted width or an uneven lower edge.'),
('Translate the reference into four decisions','Before the appointment, decide where the blend starts, whether the cheek line stays natural, how the mustache connects, and whether the bottom is rounded or more angular. These four decisions make a broad style label actionable.|Say: “I like the compact sideburn and short rounded beard in this reference. Keep my natural cheek line and connected mustache; please show me the proposed bottom outline before removing length.” Adjust those details to your own preference.'),
('Keep the finish realistic between visits','Ask your barber to demonstrate the direction to comb and which perimeter hairs can be left alone. Use a small amount of a beard product only if you like its feel; a shiny finish is not a requirement of this style. Follow the product label and avoid applying it to irritated skin.|A clean outline will soften as hair grows. Decide whether that softer phase suits you before choosing an appointment frequency. Photograph the finished cut from the front and side for your next consultation.')],
[('Is an Italian beard fade a separate cutting technique?','The name is not standardized. It usually describes a styling direction; specify the transition and outline with reference photos.'),('Does it need a sharp cheek line?','No. A natural cheek line can work with a controlled sideburn blend. Choose the amount of definition you actually want to maintain.'),('Can it work with curly hair?','Yes, the haircut and beard can be adapted independently. Your barber should assess the density and direction of beard growth.')],
['The Italian\nBeard Fade','Clean Shape,\nNatural Lines','Curly Crop &\nTidy Beard'],['Short sculpted dark beard with a low fade and natural cheek line','Swept-back hair and a tidy connected beard with a soft cheek outline','Curly crop with a short rounded beard and blended sideburn'])
add('twoblock','korean-two-block-haircut-guide','Korean Two-Block Haircut: Straight and Wavy Hair Guide',G,
'Compare straight and wavy two-block haircuts, choose the side length and fringe, and prepare a clear reference for your stylist.',
['A two-block haircut keeps a longer upper section above shorter sides and back. The contrast can be obvious or gently softened. The name does not specify one fringe length, parting or exact clipper setting.', 'Start with how your hair behaves without styling. Straight hair, natural waves, density and growth direction all change the silhouette. These illustrations help separate the cut from the finish added afterward.'],[
('Straight hair with a rounded top','A longer top can fall into a smooth, rounded outline on straight hair. Decide whether you want the fringe near the brows, swept aside or separated by a part. Ask the stylist to check the front in its natural fall before removing length.|Hair that sticks outward at the sides may need a different length or transition from the reference. Cutting that area very short is not automatically the easiest solution; discuss how it will grow and sit between appointments.'),
('Wavy hair with a softer separation','Natural waves break up the boundary between the upper and lower sections. Retaining enough top length gives the wave room to form, while selective shaping can reduce unwanted bulk. Ask the stylist to judge the dry shape as well as the wet length.|A wavy reference may include heat styling or a perm. Ask whether your hair can produce the pictured movement with the routine you are willing to repeat, rather than assuming the haircut alone creates it.'),
('Check the back and nape','The back view matters because the longer upper section can sit over a short nape in very different ways. Choose whether you prefer a visible weight line, a softer graduation or a closely tapered edge. Show a back-view reference whenever possible.|Ask how the crown will behave when you wake up or let it air-dry. A strong growth pattern can need a little extra length or a different parting to keep the shape manageable.'),
('Build a useful consultation brief','Take front, side and back references that describe the same overall cut. State how much time you spend styling, whether you use a dryer and where you normally part your hair. Discuss the amount of contrast before discussing guard numbers.|Try: “I want a longer top over shorter sides, with a soft transition rather than a pronounced shelf. Keep enough fringe to part it, and show me how the crown will sit without a salon blow-dry.”'),
('Style the shape you actually have','Start with a small amount of product and distribute it through your hands before touching the hair. Place the part first, then shape the ends rather than flattening the roots with a large dose. A light finish may preserve movement better than a heavy coating, but formulas vary.|If you use heat, follow the tool and heat-protection product instructions. Photograph your own successful everyday finish so you can explain what worked at the next cut.')],
[('Do I need straight hair?','No. Wavy hair can suit a two-block structure, but the transition and top length need to account for its movement.'),('Is a two-block the same as an undercut?','The terms can overlap. A two-block reference often emphasizes a longer upper shape above shorter sides; show the separation you want instead of relying on the name alone.'),('Will the haircut create a middle part?','It can support one, but growth direction and styling matter. Ask your stylist to test the part before finalizing the fringe.')],
['The Two-Block\nHaircut Guide','Wavy Hair,\nSofter Shape','Check the\nBack View'],['Straight dark two-block haircut with a long rounded top and short sides','Wavy two-block haircut with a soft middle part','Rear three-quarter view showing rounded top and short nape of a two-block haircut'])
add('perm','loose-wavy-perm-men-guide','Loose Wavy Perm for Men: A Consultation and Styling Guide',G,
'Plan a loose wavy perm with realistic texture references, hair-history questions and an aftercare routine agreed with your stylist.',
['A loose wavy perm aims for relaxed movement rather than a tightly defined curl. The final result depends on the hair, the cut and the professional process, so a photograph is a conversation starter rather than a guaranteed outcome.', 'Use this guide to prepare for a salon consultation. It does not provide a home chemical perm procedure. The illustrations show styling goals, not documented treatment results.'],[
('Relaxed waves through the top','Look for references that show broad bends and visible movement instead of compact ringlets. Explain whether you want lift at the roots, direction through the fringe or texture mainly at the ends. Those preferences affect the discussion about both the cut and the perm.|Bring a photo of your own hair on an ordinary day. Your stylist needs to see what you start with, not only the finished look you hope to achieve.'),
('Wavy fringe with shorter sides','A loose fringe can sit above a soft taper, but the top needs enough usable length for the intended shape. Ask the stylist how the planned texture may change the way the fringe appears once dry. Avoid choosing a very short wet length and expecting a long relaxed finish afterward.|Discuss the side profile too. You may want movement forward without excessive height, or more lift with less fringe over the forehead.'),
('A manageable styling setup','A wide-tooth comb, a suitable leave-in or styling product and a dryer attachment may be useful, but none is automatically required. Ask your stylist to demonstrate the smallest routine that works for your hair. Buying several products before the consultation can leave you with unnecessary duplicates.|If diffusing is recommended, follow the dryer instructions and the stylist’s advice on heat and handling. The desired result is a routine you can reproduce, not a complicated shelf of products.'),
('Share your complete hair history','Tell the stylist about bleaching, color, previous perms, straightening and other chemical services, including approximate dates. Mention breakage, scalp irritation and anything you do not know about past treatments. Suitability needs an individual assessment; a trend photograph cannot establish whether a service is appropriate.|Ask what assessment or strand testing the salon considers necessary, what result is realistic and whether a cut or temporary styling approach would be a better first step.'),
('Get written aftercare for your service','Washing, tying, brushing and product instructions should come from the professional who performed the service and the products used. Do not substitute a universal internet countdown for that advice. Before leaving, ask when to wash, how to dry and what to do if the texture feels unexpected.|Plan future appointments around the condition of your hair and the way new growth blends in. Repeating a chemical service on a fixed trend-driven schedule is not a substitute for reassessment.')],
[('Can a haircut alone give me these waves?','Only if your natural texture or temporary styling can create them. A cut supports movement but does not chemically change straight hair into waves.'),('Can bleached hair be permed?','Suitability depends on condition and treatment history. Discuss it with a qualified stylist before booking a chemical service.'),('How long should I wait before washing?','Follow the instructions for your particular salon service and products. Ask your stylist for written guidance rather than assuming one timing rule fits every perm.')],
['Loose Waves,\nRealistic Plans','The Wavy\nFringe Guide','Build a Simple\nWave Routine'],['Medium brown hair styled into loose relaxed waves above shorter sides','Side profile of a loose wavy fringe and soft taper','Wide-tooth comb spray bottle towel and diffuser attachment on a bathroom counter'])
add('styling','clay-vs-wax-vs-pomade','Clay vs Wax vs Pomade: Choose Your Hair Styling Finish',G,
'Compare hair clay, wax and pomade by finish, flexibility and washout, then test a small amount before committing to a new styling routine.',
['Clay, wax and pomade are useful shopping labels, but they are not precise performance standards. A formula can combine several types of ingredients, and two products with the same label can feel very different.', 'Choose by the result you want—dry texture, flexible separation or a smoother finish—and check the individual product description. This is a selection guide, not a tested ranking of brands.'],[
('Read beyond the name on the tin','Clay-labeled products often aim for a drier-looking textured finish. Waxes often emphasize separation and reshaping. Pomades commonly offer controlled, smoother styling, with shine and washout varying by formula. These are tendencies, not promises about every product.|Compare the maker’s finish, hold and application instructions side by side. A “matte pomade” and a “clay pomade” may overlap more than their names suggest, while two waxes may differ substantially.'),
('For a matte textured crop','If your goal is visible separation without much sheen, start with a product described as matte or low-shine. Work a very small amount evenly through your hands, then apply according to the label. Add more only after checking the shape in daylight.|Fine hair may look coated sooner than dense hair, and a heavy dose can collapse the movement you wanted. If the finish feels sticky or dusty, reduce the amount before deciding you need a different category of product.'),
('For a smoother side part','A side part can benefit from a formula that allows strands to sit together with some control. Choose the shine level deliberately: a restrained sheen and a wet-looking finish are different outcomes. Use a comb only after the product is distributed rather than concentrating it in one stripe.|Check whether the formula is intended for damp or dry application. Water-based and oil-based descriptions can help frame the washout question, but the full formula and your washing routine determine the experience.'),
('Match the product to your everyday routine','Ask four questions before buying: How shiny should the hair look? How much movement should remain? Will I restyle it during the day? How easily do I want it to rinse or shampoo out? Then compare only products that fit those priorities.|For a wavy two-block or longer layered cut, avoiding unnecessary weight may matter more than maximum advertised hold. For a compact side part, control may matter more than a very dry finish. Neither goal requires one compulsory ingredient.'),
('Run a simple one-product trial','Use the same haircut, similar starting moisture and a small measured amount for your first few attempts. Change one thing at a time—amount or application stage—so you can identify what helped. Note the appearance after styling, later in the day and after washing.|Keep product off irritated skin and follow label instructions. If a product causes discomfort, stop using it. A travel size or sample can make sense when available; a large tub is not better value if the finish does not suit you.')],
[('Is clay always stronger than wax?','No. Hold depends on the specific formula, amount and hair. The category name alone cannot rank performance.'),('Does pomade always look wet?','No. Pomades range from matte to high-shine finishes. Check the product’s description and application instructions.'),('Can I combine products?','You can experiment, but begin with one product so you understand its behavior. Mixing can change the finish, weight and ease of washing.')],
['Clay, Wax\nor Pomade?','A Better\nMatte Finish','Style a Softer\nSide Part'],['Three open styling tins showing clay cream paste and amber pomade with separate swatches','Man shaping a matte textured crop with his fingers','Soft side-part hairstyle with a restrained natural sheen'])
add('discovery','perfume-discovery-set-guide','How to Choose a Perfume Discovery Set You Will Actually Use',F,
'Choose a fragrance discovery set by scent range, sample format, usable volume and redemption terms, then compare scents over separate wear days.',
['A perfume discovery set should help you make a decision, not simply add small bottles to a drawer. Start by deciding what you want to learn: explore unfamiliar scent families, compare one house’s range or find something for a specific occasion.', 'The photographs are unbranded illustrations. This guide does not claim to have tested a particular set or endorse a named fragrance.'],[
('Choose the question before the box','For broad exploration, look for a set with meaningfully different descriptions rather than several close variations of a scent you already own. If you are choosing between fragrances from one brand, a focused set can be more useful than a large mixed selection.|Read the actual included names and sizes. Attractive packaging does not tell you whether the contents cover fresh, floral, woody, sweet or other directions you are curious about.'),
('Check format and usable quantity','Sprays and dab vials offer different application experiences. Choose the format you prefer and follow its directions. Check whether each vial contains the same amount and whether the package lists volume clearly; a large number of very small samples may offer fewer repeat wear opportunities than expected.|For a simple comparison, divide the delivered set price by the total stated milliliters. That does not capture everything—curation and convenience have value—but it makes differently sized sets easier to compare.'),
('Treat full-bottle credit as a condition','Some sets include a voucher toward a larger bottle, while others do not. Before paying, read the expiry date, eligible products, minimum spend, shipping charges and regional restrictions. A credit only saves money if it applies to a purchase you would actually choose.|Keep the sample until you have worn the fragrance on ordinary days. Liking a first impression on paper is a useful starting signal, not a reason to rush directly into the largest bottle.'),
('Separate quick sorting from real wearing','Use labeled blotters to identify which samples you want to revisit, then wear one candidate at a time according to its label. Record the opening impression and how it feels later during your normal routine. Keep the application reasonably consistent when comparing days.|Allow time between fragrances rather than repeatedly adding more scents to the same skin or strip. If everything begins to smell indistinct, stop the session and return another day.'),
('Finish with a shortlist, including “none”','After several wear days, sort the samples into repeat, revisit and pass. Note the reason: enjoyable but redundant, too prominent for your routine, pleasant only at the opening, or worth another full wear. That gives the set a useful outcome even if you buy no bottle.|Before ordering a winner, compare available sizes and total cost, check the retailer’s terms and consider whether you already own something that fills the same role. Finishing the research can be more valuable than expanding the collection.')],
[('Is a discovery set cheaper than individual samples?','Not always. Compare delivered price, total stated volume, sample format and the specific fragrances you want to try.'),('Should I choose a set with a voucher?','Only if its terms fit a likely purchase. Check expiry, eligible bottles and shipping costs before treating the credit as savings.'),('How many should I test in one day?','There is no useful universal number. Keep skin wear comparisons simple, take breaks and stop when the scents become difficult to distinguish.')],
['Choose Your\nDiscovery Set','Sample With\na Clear Plan','Before the\nFull Bottle'],['Six unbranded fragrance samples in a cream presentation box with blank blotters','Three perfume samples with spaced blotters and a blank testing notebook','One fragrance sample beside a clear full-size bottle and blank testing card'])
add('wardrobe','small-fragrance-wardrobe-guide','Build a Small Fragrance Wardrobe for Everyday, Work and Evening',F,
'Give your fragrances clear roles, identify overlap and set a budget before choosing bottles for everyday wear, work and evenings.',
['A fragrance wardrobe is simply a collection chosen around how you actually live. It can be one versatile scent, a pair with different moods or a few carefully chosen bottles. There is no required minimum.', 'Daily, work and evening are useful planning roles, not strict scent rules. Start with what you already own and only add something when you can explain what it contributes.'],[
('Give each bottle a reason to stay','Lay out your current fragrances and describe when you reach for each one. Use your own words: easy after a shower, comforting on a quiet day, noticeable for a dinner out. If two bottles fill the same role, that is not automatically a problem, but it helps you see whether another similar purchase would add much.|A three-bottle illustration is a planning example, not a shopping list. One fragrance can cover several roles if you enjoy wearing it that way.'),
('Choose an everyday and work option','For everyday wear, prioritize a scent you enjoy over many hours and do not need a special occasion to use. For work or shared spaces, consider the setting’s fragrance policy and the people nearby. A scent-free workplace requires a scent-free choice, regardless of the bottle’s marketing.|Do not rely on “fresh” or “clean” wording as a guarantee of low projection. Test the actual fragrance, apply according to its label and assess whether the amount feels appropriate for your environment.'),
('Make evening a mood rather than a rule','An evening fragrance might feel warmer, sweeter, drier or more textured to you, but it does not have to be heavy. Think about the setting: a small dining room, an outdoor gathering and a crowded venue invite different choices.|Try the fragrance during a normal evening before buying. A dramatic opening in a shop may be less enjoyable beside dinner or during a long trip home. Comfort and repeat use are more useful criteria than a label that says “night.”'),
('Find the gap before adding a bottle','Write a short role statement for any proposed purchase: “I want something I enjoy in warm weather that feels different from my sweet everyday scent.” Then sample options against that statement. If the best candidate largely duplicates a favorite, decide whether you want a replacement rather than an addition.|Rotate what you already own for a week before shopping. Sometimes the apparent gap is simply a bottle you stopped noticing at the back of the shelf.'),
('Set a collection budget and review it','Choose a total amount you can comfortably spend, including samples and delivery, before browsing. Compare available bottle sizes against how often you expect to wear the scent. A lower cost per milliliter does not make a large bottle economical if most of it will remain unused.|Keep bottles closed and follow their storage guidance. Periodically review which ones you reach for. The aim is a collection that supports your routine, not a shelf that keeps growing to satisfy an arbitrary number.')],
[('How many fragrances do I need?','There is no minimum. One scent you enjoy can be enough; add another only when it offers a role or experience you value.'),('Must an evening scent be strong?','No. Choose by preference and setting. Time of day does not require a particular intensity or scent family.'),('Can one perfume cover work and weekends?','Yes, where fragrance is allowed and the scent suits the setting. You do not need separate bottles just because the calendar changes.')],
['A Small\nScent Wardrobe','Your Everyday\nFragrance','An Evening\nScent Mood'],['Three unbranded clear pale green and amber perfume bottles on a stone tray','Clear perfume bottle beside a folded white shirt in morning light','Amber fragrance bottle beside a dark jacket and cream scarf in warm evening light'])
add('notes','fragrance-notes-testing-journal','Fragrance Notes Explained: A Simple Perfume Testing Journal',F,
'Understand top, heart and base notes without treating them as a stopwatch, and use a repeatable journal to compare your fragrance samples.',
['Fragrance notes describe perceived smells and creative impressions. A lemon, cedar or floral note does not necessarily mean that the named material is present as a literal ingredient. Notes are a guide to the experience, not a complete formula.', 'A useful testing journal records what you actually notice, even when it differs from the description. You do not need a trained vocabulary to recognize which fragrances you enjoy wearing.'],[
('Use note lists as a starting map','Read a list for its broad direction: bright citrus, green freshness, dry woods, soft florals or sweet warmth. These descriptions can help you choose samples, but they cannot fully communicate a fragrance’s balance. Two perfumes with overlapping notes can smell quite different.|The lemon peel and wood in the illustration are scent metaphors. They do not establish ingredients, sourcing or any property of a particular perfume.'),
('Notice change without timing a pyramid','Top, heart and base are common ways to discuss a fragrance’s development. They are not three sealed compartments that switch at exact times. Some impressions overlap, persist or become more noticeable as others soften.|Write down an early impression and revisit it later in your normal day. You can record the actual time for consistency, but avoid deciding that a fragrance has “failed” because it does not follow a rigid online timeline.'),
('Keep a short, repeatable journal','For each wear, record the fragrance name, date, application location, approximate amount and the setting. Add three plain-language observations: first impression, later impression and whether you wanted to smell it again. Finish with repeat, revisit or pass.|Use the same fields each time. “Soft woody scent; pleasant at my desk; became sweeter later; repeat” is more useful than a long list of impressive adjectives you are unsure about.'),
('Separate paper impressions from skin wear','Blotters help you sort samples without applying all of them to your skin. Label each strip and keep them apart. For a wearable fragrance, follow its application instructions when you move to a skin trial; avoid irritated skin and stop if discomfort occurs.|Paper testing and wearing are different contexts. Record which you used, and do not assume that an enjoyable blotter result settles how the fragrance will feel throughout your day.'),
('Compare patterns across several wears','Revisit favorites on separate days before buying. Look for repeated enjoyment, settings where the scent works and moments when it feels distracting. Note whether you are judging the fragrance itself or the excitement of trying something new.|Your notes need not match someone else’s review. If you like a scent but cannot name a single advertised note, that is still useful evidence for your own decision. Keep the final shortlist small enough to compare meaningfully.')],
[('Are fragrance notes an ingredient list?','No. Notes describe olfactory impressions. Consult the product’s actual ingredient information for listed ingredients.'),('Do base notes appear at an exact time?','No. The pyramid is a descriptive model; impressions can overlap and develop differently across fragrances and wearing conditions.'),('What if I cannot identify the advertised notes?','Record familiar descriptions and your level of enjoyment instead. A personal journal is useful without specialist terminology.')],
['Understand\nFragrance Notes','Test, Pause\nand Revisit','Keep a Simple\nScent Journal'],['Clear perfume bottle with lemon peel green leaf and cedarwood as scent metaphors','Woman sampling fragrance on a blotter beside a sample vial timer and notebook','Open blank scent journal with three sample vials and separate testing strips'])

if __name__=='__main__':
 existing=json.loads((R/'data/posts.json').read_text());slugs={x['post']['slug'] for x in items}
 for item in items:
  p=item['post'];p['relatedSlugs']=[x['post']['slug'] for x in items if x['post']['category']==p['category'] and x!=item][:3]
 for p in existing:
  if p['slug']=='soft-wolf-cut-men':
   p['relatedSlugs']=['korean-two-block-haircut-guide','loose-wavy-perm-men-guide','clay-vs-wax-vs-pomade'];p['dateModified']='2026-10-05'
   heading='Choose the structure before the styling product'
   if not any(s['heading']==heading for s in p['sections']):p['sections'].append(dict(heading=heading,paragraphs=['A soft wolf cut relies on a layered silhouette and retained length through the back. If you prefer a longer top above distinctly shorter sides, compare the two-block guide below before booking. If the reference depends on waves you do not naturally have, discuss whether temporary styling or a professional texture consultation is appropriate; the cut alone will not create that texture.','Bring front, side and back references and explain how much time you will spend styling. Ask the stylist to check the crown and fringe in their natural fall. For daily finishing, use the clay, wax and pomade comparison below to choose the amount of sheen and movement you want rather than assuming every layered haircut needs the same product.']))
  if p['slug']=='perfume-layering-ideas':p['relatedSlugs']=['perfume-discovery-set-guide','small-fragrance-wardrobe-guide','fragrance-notes-testing-journal']
 (R/'data/posts.json').write_text(json.dumps([x['post'] for x in items]+[p for p in existing if p['slug'] not in slugs],ensure_ascii=False,indent=2)+'\n')
 (R/'data/grooming-2026-10-05.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
 print('Prepared eight guides; connected wolf-cut and perfume-layering articles.')
